# Generated by Django 5.2.15 on 2026-06-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usergame_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_public_profile',
            field=models.BooleanField(default=True),
        ),
    ]
