# Generated by Django 5.2.15 on 2026-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_has_completed_onboarding_user_is_public_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['from_user', 'to_user'], name='core_friend_from_us_db5d10_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='core_post_created_84f629_idx'),
        ),
        migrations.AddIndex(
            model_name='usergame',
            index=models.Index(fields=['user', 'status'], name='core_userga_user_id_865767_idx'),
        ),
    ]
