# Generated by Django 5.2.15 on 2026-07-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_friendship_core_friend_from_us_db5d10_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_psn_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_xbox_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='psn_npsso',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='psn_online_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_app_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_gamertag',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_xuid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usergame',
            name='sync_source',
            field=models.CharField(blank=True, choices=[('steam', 'Steam'), ('xbox', 'Xbox'), ('psn', 'PlayStation Network')], default='', max_length=10),
        ),
    ]
