# Generated by Django 5.2.15 on 2026-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_sync_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='status',
            field=models.CharField(choices=[('playing', 'Jugando'), ('completed', 'Completado'), ('backlog', 'Pendiente'), ('wishlist', 'Lista de deseos'), ('abandoned', 'Abandonado')], default='backlog', max_length=20),
        ),
    ]
