# Generated by Django 5.2.15 on 2026-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_postcomment_parent_gamelistcomment_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Juego principal'), (1, 'DLC'), (2, 'Expansión'), (3, 'Colección'), (4, 'Expansión independiente'), (5, 'Mod'), (6, 'Episodio'), (7, 'Temporada'), (8, 'Remake'), (9, 'Remaster'), (10, 'Edición ampliada'), (11, 'Port'), (12, 'Fork'), (13, 'Colección'), (14, 'Actualización')], null=True),
        ),
    ]
