# Generated by Django 5.2.15 on 2026-08-29 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_game_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaytimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playtime_snapshots', to='core.usergame')),
            ],
            options={
                'ordering': ['recorded_at', 'pk'],
                'indexes': [models.Index(fields=['user_game', 'recorded_at'], name='core_playti_user_ga_9e0617_idx')],
            },
        ),
    ]
