# Generated by Django 5.2.17 on 2026-08-30 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_playtimesnapshot_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.gamelist'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('review', 'Reseña'), ('update', 'Actualización'), ('achievement', 'Logro'), ('list', 'Lista'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='GameListLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.gamelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game_list', 'user')},
            },
        ),
    ]
