# Generated by Django 5.2.17 on 2026-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_post_related_list_alter_post_post_type_gamelistlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='sync_app_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='usergame',
            constraint=models.UniqueConstraint(condition=models.Q(('sync_app_id', ''), _negated=True), fields=('user', 'sync_source', 'sync_app_id'), name='unique_synced_app_per_user'),
        ),
    ]
