# Generated by Django 5.2.17 on 2026-09-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usergame_sync_app_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_xbox_linked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xbox_app_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xbox_gamertag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xbox_xuid',
        ),
        migrations.AlterField(
            model_name='usergame',
            name='sync_source',
            field=models.CharField(blank=True, choices=[('steam', 'Steam'), ('psn', 'PlayStation Network')], default='', max_length=10),
        ),
    ]
